# Assignment 1
This assignment has two questions:
 - Q1: Probability
 - Q2: Linear Regression

Utilize the designated cell within this notebook to complete the exercises. As for the Python exercises:
- Refrain from altering the provided code; simply fill in the missing portions as indicated.
- Do not use any additional libraries beyond those already included in the code (e.g., NumPy and Matplotlib library).
- Make sure that the output of all code cells is visible in your submitted notebook. **The evaluator is NOT expected to execute your code before grading your submission.**
   
Please identify the authors of this assignment in the cell below.

# **Identification**

* **Name:** xxx
* **Student Number:**

* **Name:**
* **Student Number:**


---


**Note:** This work is to be done in group of **2** elements. Use this notebook to answer all the questions. At the end of the work, you should **upload** the **notebook** and a **pdf file** with a printout of the notebook with all the results in the **moodle** platform.
To generate the pdf file we have first to covert the notebook to html using the command `!jupyter nbconvert --to html "ML_project2.ipynb"`, then open the html file and printout to PDF.

## 1. Probability exercise
A city has 3 RADARs (𝐴,
𝐵, and
𝐶) in different locations to detect aerial threats.  These sensors have a stochastic detection capability as a function of range coordinates **x=**$(x_1, x_2)$, which can be modeled by a 2D Gaussian distribution $N (\mu, \Sigma)$. Any moving object appearing in the air will generate a footprint area in the detection range  of each RADAR that is used to estimate the probability of that threat be properly detected:
Each RADAR has a particular stochastic model:
 - 𝐴 is unknown but there is a dataset available;
 - 𝐵 is unknown but there is a dataset available;
 - 𝐶 is described below:

\begin{align}
\mu_C = \begin{pmatrix}
1.5 \\
1.5  
\end{pmatrix},
\end{align}

\begin{align}
\Sigma_C = \begin{pmatrix}
0.5 & 0.0 \\
0.0 & 0.5
\end{pmatrix}.
\end{align}

𝐴, 𝐵 and 𝐶 have independent sensing capabilities.

In [2]:
# Load libraries that you are allowed to use
import numpy as np
import matplotlib.pyplot as plt

a)  **characterize the detection capability of RADARs 𝐴 and 𝐵, by writing the formulas for the parameter estimates and probability density functions of each distribution.**

First, indicate all mathematical expressions that are needed to solve this exercise and then, implement the solution in Python.


Tip: use the [Latex syntaxe](https://colab.research.google.com/github/bebi103a/bebi103a.github.io/blob/main/lessons/00/intro_to_latex.ipynb#scrollTo=QOEFZmw4Z1GJ) to show the mathematical expessions.

### Mean Expression
$$
\mathbf{\mu} = \begin{pmatrix}
\mu_1 \\
\mu_2
\end{pmatrix}
$$
### Covariance Expression
$$
\mathbf{\Sigma} = \begin{pmatrix}
\sigma_{11} & \sigma_{12} \\
\sigma_{21} & \sigma_{22}
\end{pmatrix}
$$
### Probability Density Function (PDF) Expression
$$
f(\mathbf{x}) = \frac{1}{2\pi |\mathbf{\Sigma}|^{1/2}} \exp\left(-\frac{1}{2} (\mathbf{x} - \mathbf{\mu})^\top \mathbf{\Sigma}^{-1} (\mathbf{x} - \mathbf{\mu})\right)
$$

<font color='green'> ToDO!</font>

In [3]:
# Read the text file back into a NumPy array
X_A = loaded_array = np.loadtxt("ml_dataset_q1_A", delimiter=' ')
X_B = loaded_array = np.loadtxt("ml_dataset_q1_B", delimiter=' ')

In [4]:
# ToDo the code
#...

mean_A = np.array([np.mean(X_A[:, 0]), np.mean(X_A[:, 1])])
mean_B = np.array([np.mean(X_B[:, 0]), np.mean(X_B[:, 1])])
cov_A = np.cov(X_A[:, 0], X_A[:, 1])
cov_B = np.cov(X_B[:, 0], X_B[:, 1])

pdf_A = (1 / (2 * np.pi * np.sqrt(np.linalg.det(cov_A)))) * np.exp(-0.5 * np.dot(np.dot((X_A - mean_A), np.linalg.inv(cov_A)), (X_A - mean_A).T))
pdf_B = (1 / (2 * np.pi * np.sqrt(np.linalg.det(cov_B)))) * np.exp(-0.5 * np.dot(np.dot((X_B - mean_B), np.linalg.inv(cov_B)), (X_B - mean_B).T))


print("mean A = ", mean_A)
print("Cov A  = ", cov_A, "\n\r")
print("mean B = ", mean_B)
print("Cov B  = ", cov_B, "\n\r")

print("pdf_A = ", pdf_A, "\n\r")
print("pdf_B = ", pdf_B)


# ...



mean A =  [0.89750403 1.30273791]
Cov A  =  [[0.98466546 0.26778636]
 [0.26778636 1.30541953]] 

mean B =  [2.31641946 2.31896158]
Cov B  =  [[ 0.95273342 -0.28039522]
 [-0.28039522  1.39752779]] 

pdf_A =  [[0.02734601 0.07967066 0.25638363 ... 0.17433397 0.15382291 0.05004189]
 [0.07967066 0.09869635 0.2895915  ... 0.12020526 0.15969392 0.13078491]
 [0.25638363 0.2895915  0.02838919 ... 0.28148721 0.11269594 0.09214782]
 ...
 [0.17433397 0.12020526 0.28148721 ... 0.09723681 0.16110217 0.24715802]
 [0.15382291 0.15969392 0.11269594 ... 0.16110217 0.1390336  0.13212369]
 [0.05004189 0.13078491 0.09214782 ... 0.24715802 0.13212369 0.04620228]] 

pdf_B =  [[0.10886731 0.2214582  0.17897345 ... 0.11196423 0.09964373 0.14119922]
 [0.2214582  0.0629804  0.09087487 ... 0.28237005 0.24301533 0.15361109]
 [0.17897345 0.09087487 0.11039144 ... 0.22232376 0.18466679 0.15108696]
 ...
 [0.11196423 0.28237005 0.22232376 ... 0.03984861 0.12600207 0.11115934]
 [0.09964373 0.24301533 0.18466679 ... 0.



b) **Calculate the probability density of a potential threat at grid coordinate (1.5, 1.5) be detected by 𝐴. Repeat for 𝐵.** Implement the solution in Python.

In [5]:
# ToDo the code
#...

print("pdf(A = (1.5 1.5) ) =", p_A_when_x)
print("pdf(B = (1.5 1.5) ) =", p_B_when_x)

NameError: name 'p_A_when_x' is not defined

c) **What is the probability density of a threat in coordinate (1.9, 2.1) be detected by all city's RADARs ?** Implement the solution in Python. Plot the contour curves of the detection profile for each RADAR and for a threat being detected by all RADARs.

In [ ]:
# ToDo the code
#...

print("pdf(A = (1.9 2.1) ) =", p_A_when_x)
print("pdf(B = (1.9 2.1) ) =", p_B_when_x)
print("pdf(C = (1.9 2.1) ) =", p_C_when_x)
print("pdf(A, B, C) =", p_x_A_B_C)

## Curve curves
x_range        = np.linspace(-2, 6, 18)
y_range        = np.linspace(-2, 6, 18)
x_grid, y_grid = np.meshgrid(x_range, y_range)

#...


## 2. Linear regression exercise

The software of each RADAR analyses the orientations $(x_1, x_2)$ and the  signal strength ($x_3$) to calculate the range of a potential threat as $f(x) = \theta_0 + \theta_1 \sin(x_1) + \theta_2 \cos(x_2) + \theta_3 e^{x_3}$.

In [ ]:
# Load libraries that you are allowed to use
import numpy as np
import matplotlib.pyplot as plt

a) **The optimal parameters for the linear regression problem can be obtained by solving
$$ \min_{\boldsymbol{\theta}} ||\boldsymbol{y} - \boldsymbol{X}\boldsymbol{\theta}||_2^2 $$
for suitably defined matrices/vectors $\boldsymbol{\theta}$, $\boldsymbol{X}$, and $\boldsymbol{y}$. Provide explicit definitions for these matrices/vectors.**

Tip: use the [Latex syntaxe](https://colab.research.google.com/github/bebi103a/bebi103a.github.io/blob/main/lessons/00/intro_to_latex.ipynb#scrollTo=QOEFZmw4Z1GJ) to show the mathematical expessions.

<font color='green'> ToDO!</font>

b) **Find the $\boldsymbol{\hat \theta}$ to this problem by considering the following dataset $\{(x_i, y_i)\}_{i=1}^n$.**

In [ ]:
# Read the text file back into a NumPy array
dataset_q2 = loaded_array = np.loadtxt("ml_dataset_q2", delimiter=' ')
inputs     = dataset[:, 0:3]
y          = dataset[:, -2]   #label for the training

dataset_q2 = loaded_array = np.loadtxt("ml_dataset_q2_test", delimiter=' ')
inputs     = dataset[:, 0:3]  #similar inputs
y_test     = dataset[:, -1]   #label for the testing

In [ ]:
# ToDo the code
theta = np.zeros(4)  # just to prevent the code from throwing an error before it's fully implemented
#...

c) **Find the solution to the Ridge regression problem as defined in the previous exercise by completing the code below.** The variable `reg` in the code corresponds to the regularization weight $\lambda$.

In [ ]:
# ToDo the code
theta_ridge = np.zeros(4)  # just to prevent the code from throwing an error before it's fully implemented
reg         = 50.0  # regularization weight (DO NOT CHANGE)

#...

d) **Compute the mean-squared errors (MSE) of the two models in the training set and in a separate test set.** Your should avoid utilizing for-loops. Use NumPy vectorized operations instead.

In [ ]:
# ToDo the code
#...

print("MSE in the training data:")
print(f"  Linear regression (no reg.): {mse_train:.5f}")
print(f"  Ridge regression (lambda = {reg}): {mse_train_ridge:.5f}\n")

print("MSE in the test data:")
print(f"  Linear regression (no reg.): {mse_test:.5f}")
print(f"  Ridge regression (lambda = {reg}): {mse_test_ridge:.5f}\n")

# plot predictions versus ground truth
#...

e) **Would you select the Linear model or the Ridge model for deploying the solution to a potential customer?** Explain your answer.

<font color='green'> ToDO!</font>

_______________________
END of assignment!